# Setup
title:        DragoNN
tagline:      The dragonn package implements deep neural networks (DNNs) for regulatory genomics, methods for DNN interpretation, and provides tutorials showcasing dragonn models using sequence simulations.
baseurl:      "/dragonn"
paginate:     1

# About/contact
author:
  name:       Kundaje Lab
  url:        https://github.com/kundajelab

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown