# Setup
title:        DragoNN
tagline:      The dragonn package implements Deep RegulAtory GenOmic Neural Networks (DragoNNs) for predictive modeling of regulatory genomics, nucleotide-resolution feature discovery, and simulations for systematic development and benchmarking.
baseurl:      "/dragonn"

paginate:     1

# About/contact
author:
  name:       Kundaje Lab
  url:        https://github.com/kundajelab

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

# include subdirectories
keep_files: ["_site/html/"]
