# Setup
title:        DragoNN
tagline:      DragoNN provides a toolkit to learn how to model and interpret regulatory sequence data using deep learning.
baseurl:      "/dragonn"

paginate:     1

# About/contact
author:
  name:       Kundaje Lab
  url:        https://github.com/kundajelab

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

# include subdirectories
keep_files: ["_site/html/"]
